### ISSUE TITLE
problem with =remotes::install_github("unhcr/koboloadeR", Ncpus=4) and  remotes::install_github('unhcr-web/unhcRstyle')

### ISSUE THREAD

**Issue by semivumbi** [mrdwab/koboloadeR#11]
Hello every, happy new year can some body help me to resolve this problem: her is the bug: > remotes::install_github("unhcr/koboloadeR", Ncpus=4)
Error: Failed to install 'unknown package' from GitHub:
  cannot open URL 'https://api.github.com/repos/unhcr/koboloadeR/contents/DESCRIPTION?ref=HEAD'
> remotes::install_github('unhcr-web/unhcRstyle')
Error: Failed to install 'unknown package' from GitHub:
  cannot open URL 'https://api.github.com/repos/unhcr-web/unhcRstyle/contents/DESCRIPTION?ref=HEAD'

**Comment by mrdwab** [comment]
Hi @semivumbi , I think perhaps you meant to post this under the unhcr's account?
