### ISSUE TITLE
Kobo data viewer API

### ISSUE THREAD

**Issue by cindyblt** [mrdwab/koboloadeR#12]
Hello
I've just Installed the koboloadeR package, ran the kobo_apps("data_viewer") but the API seems not working. Any suggestions about that? 
![Screenshot (44)](https://user-images.githubusercontent.com/79452674/108701346-1ce6ad80-7508-11eb-998e-6efbce31a0eb.png)

**Comment by mrdwab** [comment]
Hi @cindyb-kobo. I'm not actively developing this package and the API has definitely changed. You may want to look at https://github.com/unhcr/koboloadeR instead. Thanks!

**Comment by cindyblt** [comment]
Thanks for your prompt answer!
