### ISSUE TITLE
koboloadeR in CRAN

### ISSUE THREAD

**Issue by knsamati** [mrdwab/koboloadeR#8]
Hi. thank for this great work. There is a plan to put koboloadeR in CRAN?
I want to use it in shiny app but i don't know if it will work after deploy.

**Comment by mrdwab** [comment]
Hi @knsamati . Some of the functions write data to the user's environment (as they are potentially downloading the dataset). To my knowledge, that's not allowed in CRAN packages, which is one of the reasons I've not submitted the package. 

There aren't too many functions in this package, so you could possibly just copy the functions directly into your Shiny app if for any reason the package isn't working once you deploy it.

**Comment by knsamati** [comment]
thank you very much
